### PR TITLE
Multiple fixes including bookmarklet, useragents and fixing www sites being different from non www sites.

### PR DESCRIPTION
**Pull request by lindell**
Updated bookmarklet so that browser history is working

### CODE REVIEW

**Comment by lindell** [comment]
Now fixed a lot of stuff with how the user agents is handled. Some cleaning of spaghetti code but also bugs regarding it

**Comment by phixofor** [comment]
Wow! This is much appreciated. I am sorry to say that I am too poor of a developer to assess if it works correctly. I will have to try it out first, but it doesn't strike me as anything too complex.

For now, I'm just wondering if helpfunctions.php is needed? Since this is a pretty straight forward application, I do not reuse functions a lot, so I really like to keep them within the same file for an easier overview (I had the same issue with dbhandler.php but let it slide because I didn't want to interfere).

**Comment by lindell** [comment]
Keeping things in one file is not making anything easier. Maybe it was not necessary with only one function but the urlfix function was really not belonging in the index.php file

**Comment by phixofor** [comment]
Merged, uploaded and live! Thank you for your contribution :D

**Pull request merged**
